dekunobouのC FFI部分を本家のWeb版と共用するようにした
yojo-art/dekunobou_bot pull request #8
Opened 2024-09-08 03:05 UTC by jj1guj

https://github.com/yojo-art/dekunobou_bot/pull/6

2024-09-11 16:45 UTC, kozakura913 requested changes

2024-09-11 16:45 UTC, kozakura913 commented on src/main.rs
> +extern crate dekunobou;
`use dekunobou;`が新しい記法だから変えたほうが良さそう

2024-09-11 16:45 UTC, kozakura913 commented on Cargo.toml
> +dekunobou = { path = "dekunobou/web/api/lib/dekunobou" }
深いpath指定してるのなんか気持ち悪いけどライブラリ専用リポジトリになってないからしょうがないのかなぁ...

2024-09-11 17:00 UTC, jj1guj commented on Cargo.toml
> +dekunobou = { path = "dekunobou/web/api/lib/dekunobou" }
パスが深すぎて直感的にイけてないってのはわかるしなんとかしたいお気持ちでいるのでWeb版でもなんとかしたい気持ちでいる
ただこのリポジトリをcloneすればブラウザでも遊べるってスタイルを崩したくないってスタンスでいる
これを踏まえるとこのリポジトリ直下に`api`ディレクトリ作ってその下にバックエンドのコードを全て格納するのが良かったりする？

2024-09-11 17:18 UTC, kozakura913 commented on Cargo.toml
> +dekunobou = { path = "dekunobou/web/api/lib/dekunobou" }
依存関係を別リポジトリに分割しちゃってpathで読み込まずにgit指定で読み込むとかやれば綺麗にいけそうだけど
安定したブランチを用意しとけばいちいち利用側で対象コミット変えなくてもブランチ指定で持ってこれるし

2024-09-13 15:28 UTC, jj1guj commented on src/main.rs
> +extern crate dekunobou;
65ee72f2d1b61523d74a872cd7c3682f57c05715

2024-09-13 15:31 UTC, jj1guj commented on Cargo.toml
> +dekunobou = { path = "dekunobou/web/api/lib/dekunobou" }
dekunobou-ffiみたいなリポジトリ作ってffi向けのC++ファイルとCMakeLists.txtを置いとくイメージ？

2024-09-13 18:56 UTC, kozakura913 commented on Cargo.toml
> +dekunobou = { path = "dekunobou/web/api/lib/dekunobou" }
libdekunobouに汎用FFI用のファイル置いてdekunobou-sysにrust用バインディングかな？
1関数には大げさな気がするけど将来増えるかもしれないし

2024-09-14 07:48 UTC, jj1guj commented on Cargo.toml
> +dekunobou = { path = "dekunobou/web/api/lib/dekunobou" }
とりあえず2つリポジトリ作ってCargo.tomlでdekunobou-sysのリポジトリを指定してみたが再帰的にサブモジュールをクローンしてなくてどうしようか悩み中。
現状libdekunobou側でcmake時にdekunobouをクローンするように書き換えてみてるけど難航している
https://github.com/jj1guj/libdekunobou
https://github.com/jj1guj/dekunobou-sys

2024-09-15 17:22 UTC, jj1guj commented on Cargo.toml
> +dekunobou = { path = "dekunobou/web/api/lib/dekunobou" }
GPT-4o1に聞いたらdekunobou-sys側で`git submodule --init --recursive`すればよくね？って言われたのでそうするようにして解決
76af2c6d98641db1d61b15f39f8384777a7df7ff

2024-09-15 23:47 UTC, kozakura913 commented on .gitmodules
> -[submodule "dekunobou"]
空ファイルいらない気がする

2024-09-15 23:47 UTC, kozakura913 commented on Cargo.toml
> +dekunobou = { git = "https://github.com/jj1guj/dekunobou-sys", branch = "main" }
mainブランチに破壊的変更入るとビルド通らなくなるのがなんかなぁって気がしつつある程度は修正反映されてほしいしなぁの気持ち
タグ指定とかコミット指定だと固定されちゃって修正も反映されないし悩ましい

2024-09-15 23:48 UTC, kozakura913 approved these changes

2024-09-16 07:32 UTC, jj1guj commented on .gitmodules
> -[submodule "dekunobou"]
消した
[2f4236f](https://github.com/yojo-art/dekunobou_bot/pull/8/commits/2f4236f5b1b2e9c62d194e599b0da53fc776ac1e)

2024-09-16 07:35 UTC, jj1guj commented on Cargo.toml
> +dekunobou = { git = "https://github.com/jj1guj/dekunobou-sys", branch = "main" }
多分FFIとRustバインディング部分に破壊的変更が入らない気がしている…
というのも本家で予定している変更が探索部分の高速化くらいしかないので…

2024-09-16 08:46 UTC, merged